const students = [
  {
    id: "PS10001",
    name: "Nguyễn Văn An",
    age: 20,
    gender: "Nam",
    major: "Công nghệ thông tin",
    gpa: 3.2,
  },
  {
    id: "PS10002",
    name: "Trần Thị Bình",
    age: 21,
    gender: "Nữ",
    major: "Kế toán",
    gpa: 3.5,
  },
  {
    id: "PS10003",
    name: "Lê Minh Cường",
    age: 19,
    gender: "Nam",
    major: "Marketing",
    gpa: 3.0,
  },
  {
    id: "PS10004",
    name: "Phạm Ngọc Diễm",
    age: 22,
    gender: "Nữ",
    major: "Quản trị kinh doanh",
    gpa: 3.6,
  },
  {
    id: "PS10005",
    name: "Hoàng Tuấn Anh",
    age: 20,
    gender: "Nam",
    major: "Thiết kế đồ họa",
    gpa: 2.9,
  },
  {
    id: "PS10006",
    name: "Võ Thị Hạnh",
    age: 21,
    gender: "Nữ",
    major: "Du lịch – Nhà hàng",
    gpa: 3.4,
  },
  {
    id: "PS10007",
    name: "Đặng Quốc Khánh",
    age: 23,
    gender: "Nam",
    major: "Công nghệ ô tô",
    gpa: 3.1,
  },
  {
    id: "PS10008",
    name: "Nguyễn Thùy Linh",
    age: 19,
    gender: "Nữ",
    major: "Ngôn ngữ Anh",
    gpa: 3.7,
  },
  {
    id: "PS10009",
    name: "Bùi Đức Long",
    age: 22,
    gender: "Nam",
    major: "An ninh mạng",
    gpa: 3.3,
  },
  {
    id: "PS10010",
    name: "Trương Mỹ Phương",
    age: 20,
    gender: "Nữ",
    major: "Thương mại điện tử",
    gpa: 3.8,
  },
];

export default students;
